core/urls.py
from django.urls import path
from .views import home, product, ItemDetailView, add_to_cart, remove_from_cart, ProductView, OrderSummaryView, remove_single_from_cart, add_single_to_cart, checkingout, CheckOutView, support, add_coupon, account_orders

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/', ProductView.as_view(), name='catalogue'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove-from-cart'),
    path('remove-single-from-cart/<slug>',
         remove_single_from_cart, name='remove-single-from-cart'),
    path('add-single-from-cart/<slug>',
         add_single_to_cart, name='add-single-to-cart'),
    path('checking-out/', checkingout, name='checking-out'),
    path('support', support, name='support'),
    path('add-coupon/', add_coupon, name='add-coupon'),
    path('account/orders/', account_orders, name='account-orders'),
]

goldenshoeecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

core/models.py
from django.db import models
from django.conf import settings
from django_countries.fields import CountryField
from django.shortcuts import reverse

CATEGORY_CHOICES = (
    ('MS', 'Men\'s Sportwear'),
    ('MEW', 'Men\'s Evening Wear'),
    ('MC', 'Men\'s Casual'),
    ('WS', 'Women\'s Sportwear'),
    ('WEW', 'Women\'s Evening Wear'),
    ('WC', 'Women\'s Casual'),
    ('O', 'Other')
)

LABEL_CHOICES = (
    ('D', 'danger'),
    ('P', 'primary'),
    ('S', 'secondary'),
    ('I', 'info')
)

STATUS_CHOICES = (
    ('P', 'Pending'),
    ('O', 'Ordered'),
    ('D', 'Delivered'),
    ('R', 'Refunded')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=3)
    label = models.CharField(choices=LABEL_CHOICES,
                             max_length=1, blank=True, null=True)
    slug = models.SlugField()
    description = models.TextField()
    release_date = models.DateTimeField()
    brief_desc = models.CharField(max_length=50, blank=True, null=True)
    image = models.ImageField()
    stock = models.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

    class Meta:
        ordering = ['-release_date']


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_item_discount_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_item_discount_price()

    def get_total_price(self):
        if self.item.discount_price:
            return self.get_total_item_discount_price()
        else:
            return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        'BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    status = models.CharField(choices=STATUS_CHOICES,
                              max_length=1, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_price()
        if self.coupon:
            total -= self.coupon.value
        return total

    def get_total_items(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.quantity
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    post_code = models.CharField(max_length=15)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    value = models.FloatField()

    def __str__(self):
        return self.code

templates/account-orders.html
{% extends "base.html" %}

{% block content %}
<div class="container my-5">
    <section class="dark-grey-text text-center mb-5">
        <h3 class="font-weight-bold mb-5">Account Order History</h3>
        {% if account_orders %}
        {% for order in account_orders %}
        <div class="card mb-5">
            <div class="card-body">
                <table class="table table-responsive-md mb-0">
                    <thead>
                        <tr>
                            <th>
                                <strong>Order {{ forloop.counter }}</strong>
                            </th>
                            <th>
                                <strong>Item</strong>
                            </th>
                            <th>
                                <strong>Price</strong>
                            </th>
                            <th>
                                <strong>Quantity</strong>
                            </th>
                            <th>
                                <strong>Total Item Price</strong>
                            </th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for orderitem in order.items.all %}
                        <tr>
                            <td></td>
                            <td scope="row">{{ orderitem.item.title }}</td>
                            <td>{% if orderitem.item.discount_price %}
                                <del>£{{ orderitem.item.price|floatformat:2 }}</del>
                                £{{ orderitem.item.discount_price|floatformat:2 }}
                                {% else %}
                                £{{ orderitem.item.price|floatformat:2 }}
                                {% endif %}</td>
                            <td>{{ orderitem.quantity }}</td>
                            <td>{% if orderitem.item.discount_price %}
                                £{{ orderitem.get_total_item_discount_price|floatformat:2 }}
                                {% else %}
                                £{{ orderitem.get_total_item_price|floatformat:2 }}
                                {% endif %}</td>
                        </tr>
                        {% endfor %}
                        {% if order.coupon %}
                        <tr>
                            <td colspan="1"><b>Promo code:</b></td>
                            <td colspan="1"><b>{{ order.coupon.code }}</b></td>
                            <td colspan="2"></td>
                            <td colspan="1"><b>- £{{ order.coupon.value|floatformat:2 }}</b></td>

                        </tr>
                        {% endif %}
                        {% if order.get_total %}
                        <tr>

                            <td colspan="1"><b>Order Total:</b></td>
                            <td colspan="3"></td>
                            <td colspan="1"><b>£{{ order.get_total|floatformat:2 }}</b></td>

                        </tr>
                        {% endif %}
                    </tbody>

                </table>
                <div class="card-body float-left text-left">
                    {% if order.ordered_date %}
                    <h5>Order Date: {{ order.ordered_date }}</h5>
                    {% endif %}
                    {% if order.billing_address %}
                    <h5>Order Address: {{ order.billing_address.street_address }},
                        {{ order.billing_address.post_code }}</h5>
                    {% endif %}
                    {% if order.status %}
                    <h5>Order Status: {{ order.get_status_display }}</h5>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}

    </section>
</div>
{% endblock %}

templates/catalogue-page.html
{% extends "base.html" %}

{% block title %}
<title>Products</title>
{% endblock %}

<body>
    {% block content %}

    <main>
        <div class="container">

            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

                <span class="navbar-brand">Categories:</span>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">All
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Men's Sports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Women's Sports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Casual Footwear</a>
                        </li>

                    </ul>

                    <form class="form-inline">
                        <div class="md-form my-0">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                        </div>
                    </form>
                </div>
            </nav>
            <section class="text-center mb-4">
                <div class="row wow fadeIn">
                    {% for item in object_list %}

                    <div class="col-lg-3 col-md-6 mb-4">

                        <div class="card">

                            <div class="view overlay card-height">
                                <img src="{{ item.image.url }}" class="card-img-top product-image center">
                                <a href="{{ item.get_absolute_url }}">
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>

                            <div class="card-body text-center">

                                <a href="{{ item.get_absolute_url }}" class="grey-text">
                                    <h5>{{ item.get_category_display }}</h5>
                                </a>
                                <h5>
                                    <strong>
                                        <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                                            <br>
                                            {% if item.get_label_display %}
                                            <span class="badge badge-pill {{ item.get_label_display }}-color">
                                                {% if item.get_label_display == "primary" %} New
                                                {% elif item.get_label_display == "danger" %} Sale
                                                {% elif item.get_label_display == "secondary" %} Seasonal
                                                {% elif item.get_label_display == "info" %} Limited {% endif %}
                                            </span>
                                            {% else %}
                                            <br>
                                            <span class="badge badge-pill"></span>
                                            {% endif %}
                                        </a>
                                    </strong>
                                </h5>

                                <h4 class="font-weight-bold blue-text">
                                    <strong>£
                                        {% if item.discount_price %}
                                        {{ item.discount_price|floatformat:2 }}
                                        {% else %}
                                        {{ item.price|floatformat:2 }}
                                        {% endif %}
                                    </strong>
                                </h4>

                            </div>

                        </div>

                    </div>

                    {% endfor %}
                </div>
            </section>

            {% if is_paginated %}
            <nav class="d-flex justify-content-center wow fadeIn">
                <ul class="pagination pg-blue">

                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}

                    <li class="page-item active">
                        <a class="page-link" href="?page={{ page_obj.number}}">{{ page_obj.number }}
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    </li>

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </main>

    {% endblock %}

</body>

templates/home-page.html
{% extends "base.html" %}

<head>
  {% block title %}
  <title>Home</title>
  {% endblock title %}
</head>

<body>
  {% block content %}

  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner" role="listbox">

      <div class="carousel-item active">
        <div class="view"
          style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Spring Release Now Available!</strong>
              </h1>
              <p>
                <strong>Our latest seasonal release is now available online and in-store</strong>
              </p>
              <p class="mb-4 d-none d-md-block">
                <strong>This seasonal is the spring release, this includes new products from brands such as Christian
                  Louboutin, Jimmy Choo, Chanel and many more!</strong>
              </p>
              <a target="_blank" href="{% url 'core:catalogue' %}" class="btn btn-outline-white btn-lg">Start
                browsing
                <i class="fas fa-cart-plus"></i>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="carousel-item">
        <div class="view"
          style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Back To Work Range</strong>
              </h1>
              <p>
                <strong>Christmas holidays are over, but that isnt a reason to be sad</strong>
              </p>
              <p class="mb-4 d-none d-md-block">
                <strong>Our back to work range will brighten up your day and your style at the same time, use coupon
                  'BackToWork' at checkout for £10 off your next order!</strong>
              </p>
              <a target="_blank" href="{% url 'core:catalogue' %}" class="btn btn-outline-white btn-lg">Start
                browsing
                <i class="fas fa-cart-plus"></i>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="carousel-item">
        <div class="view"
          style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Birthday Suprise</strong>
              </h1>
              <p>
                <strong>Is it your birthday? Come claim a gift from us!</strong>
              </p>
              <p class="mb-4 d-none d-md-block">
                <strong>If it is your birthday come into one of our stores to receive a little something from us to you
                  on your special day.</strong>
              </p>
              <i class="fas fa-birthday-cake"></i>
              <p><small>T&C apply</small></p>
            </div>
          </div>
        </div>
      </div>

    </div>

    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="container my-5">
    <hr>
    <div class="card-deck">

      <div class="card">
        <div class="card-body">
          <i class="fas fa-truck"></i>
          <h4 class="card-title">Shipping</h4>
          <hr>
          <p class="card-text">We are able to ship our stock directly to your front door!
          </p>
        </div>
        <div class="rounded-bottom mdb-color lighten-3 text-center pt-3">
          <ul class="list-unstyled list-inline font-small">
            <li class="list-inline-item pr-2 white-text"><a href="{% url 'core:support' %}">Find out more <i
                  class="fas fa-angle-double-right"></i></a>
            </li>
          </ul>
        </div>
      </div>



      <div class="card">
        <div class="card-body">
          <i class="fas fa-hands-helping"></i>
          <h4 class="card-title">Support</h4>
          <hr>
          <p class="card-text">Need some help? Check out our support section for more information and details on how to
            contact us.
          </p>
        </div>
        <div class="rounded-bottom mdb-color lighten-3 text-center pt-3">
          <ul class="list-unstyled list-inline font-small">
            <li class="list-inline-item pr-2 white-text"><a href="{% url 'core:support' %}">Go to support <i
                  class="fas fa-angle-double-right"></i></a>
            </li>
          </ul>
        </div>
      </div>


      <div class="card">
        <div class="card-body">
          <i class="fas fa-gift"></i>
          <h4 class="card-title">Gift</h4>
          <hr>
          <p class="card-text">Buying an item as a gift? Let us know and we can arrange discrete delivery and gift
            wrapping.
          </p>
        </div>
        <div class="rounded-bottom mdb-color lighten-3 text-center pt-3">
          <ul class="list-unstyled list-inline font-small">
            <li class="list-inline-item pr-2 white-text"><a href="{% url 'core:support' %}">Read more <i
                  class="fas fa-angle-double-right"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  {% endblock content %}
</body>

</html>

templates/nav.html
{% block navbar %}
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <a class="navbar-brand waves-effect" href="/">
            <strong class="blue-text">GoldenShoes</strong>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto ">
                <li class="nav-item {% if current == 'home' %}active{% endif %} mr-1">
                    <a class="nav-link waves-effect" href="/">Home
                        {% if current == 'home' %} <span class="sr-only">(current)</span>{% endif %}
                    </a>
                </li>
                <li class="nav-item {% if current == 'products' %}active{% endif %}">
                    <a class="nav-link waves-effect" href="/product">Products</a>
                    {% if current == 'products' %} <span class="sr-only">(current)</span>{% endif %}
                </li>
            </ul>

            <!-- Right -->
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                <li class="nav-item {% if current == 'cart' %}active{% endif %}">
                    <a class="nav-link waves-effect" href="{% url 'core:order-summary' %}">
                        <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                        <i class="fas fa-shopping-cart"></i> Cart
                    </a>
                </li>
                <li class="nav-item {% if current == 'support' %}active{% endif %}">
                    <a class="nav-link waves-effect" href="/support">Support</a>
                    {% if current == 'support' %} <span class="sr-only">(current)</span>{% endif %}
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Account
                    </a>
                    <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
                        <a class="dropdown-item" href="{% url 'core:account-orders' %}">Orders</a>
                        <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
                    </div>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                        <span class="clearfix d-sm-inline-block"> Login </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                        <span class="clearfix d-sm-inline-block"> SignUp </span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% endblock navbar %}

templates/order-summary.html
{% extends "base.html" %}

<head>
    {% block title %}
    <title>Order</title>
    {% endblock title %}
</head>

<body>
    {% block content %}
    <main>
        <div class="container">
            <div class="table-responsive text-nowrap">

                <h2>Order Summary</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Item</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total Item Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for orderitem in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><a href="{{ orderitem.item.get_absolute_url }}">{{ orderitem.item.title }}</a></td>
                            <td>{% if orderitem.item.discount_price %}
                                <del>£{{ orderitem.item.price|floatformat:2 }}</del>
                                £{{ orderitem.item.discount_price|floatformat:2 }}
                                {% else %}
                                £{{ orderitem.item.price|floatformat:2 }}
                                {% endif %}</td>
                            <td><a href="{% url 'core:remove-single-from-cart' orderitem.item.slug %}"><i
                                        class="fas fa-minus mr-2"></i></a>{{ orderitem.quantity }}<a
                                    href="{% url 'core:add-single-to-cart' orderitem.item.slug %}"><i
                                        class="fas fa-plus ml-2"></i></a></td>
                            <td>{% if orderitem.item.discount_price %}
                                £{{ orderitem.get_total_item_discount_price }}
                                (Saving £{{ orderitem.get_amount_saved|floatformat:2 }})
                                {% else %}
                                £{{ orderitem.get_total_item_price|floatformat:2 }}
                                {% endif %}
                                <a style="color:red" href="{% url 'core:remove-from-cart' orderitem.item.slug %}"><i
                                        class="fas fa-trash float-right"></i></a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td>Your cart is empty</td>
                        </tr>
                        <tr>
                            <td>
                                <a href=" {% url 'core:catalogue' %}" class="btn btn-warning">Continue Shopping</a>
                            </td>
                        </tr>

                        {% endfor %}
                        {% if object.coupon %}
                        <tr>
                            <td colspan="1"><b>Promo code:</b></td>
                            <td colspan="3"><b>{{ object.coupon.code }}</b></td>
                            <td colspan="1"><b>- £{{ object.coupon.value|floatformat:2 }}</b></td>

                        </tr>
                        {% endif %}
                        {% if object.get_total %}
                        <tr>

                            <td colspan="4"><b>Order Total:</b></td>
                            <td colspan="1"><b>£{{ object.get_total|floatformat:2 }}</b></td>

                        </tr>
                        <tr>

                            <td colspan="5"><a href="{% url 'core:catalogue' %}" class="btn btn-warning">Continue
                                    Shopping</a><a href="/checkout/" class="btn btn-default float-right">Checkout</a>
                            </td>

                        </tr>
                        {% endif %}
                    </tbody>
                </table>
                <div>

                </div>
            </div>
        </div>
    </main>
    {% endblock content %}
</body>

</html>